name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.4'

    - name: Start Docker services
      run: |
        docker-compose -f docker-compose.test.yaml up -d

    - name: Install mod
      run: |
        go mod tidy

    - name: Run tests
      run: |
        go test -v ./...

    - name: Stop Docker services
      if: always()
      run: |
        docker-compose -f docker-compose.test.yaml down -v
Ñ‘